name: Build SvelteKit App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build

    env:
      PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
      PUBLIC_BEARER_TOKEN: ${{ secrets.PUBLIC_BEARER_TOKEN }}
      COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
      COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}

    permissions:
      contents: read
      packages: write # Grant write permissions to the GITHUB_TOKEN for publishing packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            PUBLIC_API_URL=${{ env.PUBLIC_API_URL }}
            PUBLIC_BEARER_TOKEN=${{ env.PUBLIC_BEARER_TOKEN }}
      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
