name: Build and Deploy to remote server
on:
  push:
    branches:
      - test

  
jobs:
  build-site:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.5
          
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21.7
          cache: pnpm
          
      - name: Install Dependencies
        run: pnpm i
        
      - name: Build site
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'build/'

  deploy:
    needs: build-site
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: build/*
        target: /home/syamil/gahmen-sg/caddy/site
  
